name: IaC Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          # Isse pipeline PASS ho jayegi, lekin galtiyan logs mein dikhengi
          soft_fail: true 
          output_format: cli